package com.omega_r.libs.entities.extensions

import platform.Foundation.NSString
import platform.Foundation.create
import platform.Foundation.pathExtension

internal const val DEFAULT_MIME_TYPE = "application/octet-stream"
internal val mimeTypes = mapOf(
    "html" to "text/html",
    "htm" to "text/html",
    "shtml" to "text/html",
    "css" to "text/css",
    "xml" to "text/xml",
    "gif" to "image/gif",
    "jpeg" to "image/jpeg",
    "jpg" to "image/jpeg",
    "js" to "application/javascript",
    "atom" to "application/atom+xml",
    "rss" to "application/rss+xml",
    "mml" to "text/mathml",
    "txt" to "text/plain",
    "jad" to "text/vnd.sun.j2me.app-descriptor",
    "wml" to "text/vnd.wap.wml",
    "htc" to "text/x-component",
    "png" to "image/png",
    "tif" to "image/tiff",
    "tiff" to "image/tiff",
    "wbmp" to "image/vnd.wap.wbmp",
    "ico" to "image/x-icon",
    "jng" to "image/x-jng",
    "bmp" to "image/x-ms-bmp",
    "svg" to "image/svg+xml",
    "svgz" to "image/svg+xml",
    "webp" to "image/webp",
    "woff" to "application/font-woff",
    "jar" to "application/java-archive",
    "war" to "application/java-archive",
    "ear" to "application/java-archive",
    "json" to "application/json",
    "hqx" to "application/mac-binhex40",
    "doc" to "application/msword",
    "pdf" to "application/pdf",
    "ps" to "application/postscript",
    "eps" to "application/postscript",
    "ai" to "application/postscript",
    "rtf" to "application/rtf",
    "m3u8" to "application/vnd.apple.mpegurl",
    "xls" to "application/vnd.ms-excel",
    "eot" to "application/vnd.ms-fontobject",
    "ppt" to "application/vnd.ms-powerpoint",
    "wmlc" to "application/vnd.wap.wmlc",
    "kml" to "application/vnd.google-earth.kml+xml",
    "kmz" to "application/vnd.google-earth.kmz",
    "7z" to "application/x-7z-compressed",
    "cco" to "application/x-cocoa",
    "jardiff" to "application/x-java-archive-diff",
    "jnlp" to "application/x-java-jnlp-file",
    "run" to "application/x-makeself",
    "pl" to "application/x-perl",
    "pm" to "application/x-perl",
    "prc" to "application/x-pilot",
    "pdb" to "application/x-pilot",
    "rar" to "application/x-rar-compressed",
    "rpm" to "application/x-redhat-package-manager",
    "sea" to "application/x-sea",
    "swf" to "application/x-shockwave-flash",
    "sit" to "application/x-stuffit",
    "tcl" to "application/x-tcl",
    "tk" to "application/x-tcl",
    "der" to "application/x-x509-ca-cert",
    "pem" to "application/x-x509-ca-cert",
    "crt" to "application/x-x509-ca-cert",
    "xpi" to "application/x-xpinstall",
    "xhtml" to "application/xhtml+xml",
    "xspf" to "application/xspf+xml",
    "zip" to "application/zip",
    "epub" to "application/epub+zip",
    "docx" to "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "xlsx" to "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "pptx" to "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "mid" to "audio/midi",
    "midi" to "audio/midi",
    "kar" to "audio/midi",
    "mp3" to "audio/mpeg",
    "ogg" to "audio/ogg",
    "m4a" to "audio/x-m4a",
    "ra" to "audio/x-realaudio",
    "3gpp" to "video/3gpp",
    "3gp" to "video/3gpp",
    "ts" to "video/mp2t",
    "mp4" to "video/mp4",
    "mpeg" to "video/mpeg",
    "mpg" to "video/mpeg",
    "mov" to "video/quicktime",
    "webm" to "video/webm",
    "flv" to "video/x-flv",
    "m4v" to "video/x-m4v",
    "mng" to "video/x-mng",
    "asx" to "video/x-ms-asf",
    "asf" to "video/x-ms-asf",
    "wmv" to "video/x-ms-wmv",
    "avi" to "video/x-msvideo"
)

fun String.getMimeType(): String =
    mimeTypes[NSString.create(string = this).pathExtension] ?: DEFAULT_MIME_TYPE
